# Generated by Django 5.1.5 on 2025-03-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
