# Generated by Django 5.1.5 on 2025-03-30 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0002_account_password_manager_password_alter_manager_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='community_checkin.manager'),
            preserve_default=False,
        ),
    ]
