# Generated by Django 5.1.5 on 2025-05-02 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0003_item_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='code',
            field=models.CharField(default=uuid.UUID('35d3ea71-636b-4977-99e1-8ea1ac15a366'), max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
