# Generated by Django 5.1.5 on 2025-05-02 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0004_remove_account_age_alter_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='code',
            field=models.CharField(default=uuid.UUID('d770dc5f-071c-4390-afb5-b860b2d38353'), max_length=36, unique=True),
        ),
    ]
