# Generated by Django 5.1.5 on 2025-05-02 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0005_alter_manager_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='code',
            field=models.CharField(default=uuid.UUID('fd0da178-3751-44d0-ab75-4e0bf8c9bb29'), max_length=36, unique=True),
        ),
    ]
