# Generated by Django 5.1.5 on 2025-05-02 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0006_alter_manager_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f7df021e-3c49-4ce4-8d1a-d49729921543'), primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Identifiers',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='code',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('5fa29362-5003-41b7-8d9f-504fad025ea8'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('55fd4fd0-66d4-4e28-81fe-5eb07cc6f217'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f783184e-abaa-406c-8609-84fd9e1075ee'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='loan',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_checkin.item'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loanee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_checkin.account'),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
