# Generated by Django 5.1.5 on 2025-05-02 18:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0008_alter_account_id_alter_item_id_alter_loan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc2a658b-37c1-418f-a29a-1dfdf00da8d7'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d096691f-5233-4f69-bfbd-0fe16fa2b31e'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ec3cd5c-ad34-45c0-9b33-c903c8ddc274'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e887dc0-a893-46ef-a82d-16e2cda8bf6c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
