# Generated by Django 5.1.5 on 2025-05-02 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0010_alter_account_id_alter_item_id_alter_loan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4fa8928e-eb8c-4bfd-98e0-ab207a26e977'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4ae27737-e1f2-4c75-a0fe-13d70f4efffa'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa305197-a66f-4e75-aa50-c76b1c15d289'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e86d4d4-cd40-4d30-9397-ff93f68a9461'), primary_key=True, serialize=False, unique=True),
        ),
    ]
