# Generated by Django 5.1.5 on 2025-05-02 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0012_alter_account_id_alter_item_id_alter_loan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66b35e6d-9653-4124-9fff-e8636db249a5'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c66a8a5f-d075-44c5-9fd7-a5b77188110f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75f03980-cffc-45cf-9fb4-423bc12b811c'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d540a92f-7b73-4d82-834c-3ba29286053a'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['id'], name='account_id_ind'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['name', 'password'], name='account_login_ind'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['id'], name='item_id_ind'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['owner'], name='item_owner_ind'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loanee'], name='loan_loanee_ind'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['start_date'], name='loan_sdate_ind'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['name', 'password'], name='manager_login_ind'),
        ),
    ]
