# Generated by Django 5.1.5 on 2025-05-02 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0013_alter_account_id_alter_item_id_alter_loan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac9a8c9d-fae4-48eb-89df-4c55f84822f6'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9072ffd3-472a-41dd-a4e2-57bd4288034f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('097feb69-0000-4c01-8221-c892cb474889'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ec01995-2126-45a3-b221-41a5e58f0359'), primary_key=True, serialize=False, unique=True),
        ),
    ]
