# Generated by Django 5.1.5 on 2025-05-05 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0015_alter_account_id_alter_item_id_alter_loan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=uuid.UUID('8809e055-2609-41e6-809e-e83b77bbec1d'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default=uuid.UUID('b5ca60e1-68d6-41ae-94eb-f48dbcc4cfbc'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.CharField(default=uuid.UUID('1975a91e-5814-43ac-9a2a-2f27965bf451'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_checkin.item'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_checkin.account'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.CharField(default=uuid.UUID('5859906e-677d-42e6-9e2d-2bbe60687668'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
