# Generated by Django 5.1.5 on 2025-05-05 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0016_alter_account_id_alter_item_id_alter_loan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=uuid.UUID('f3993941-a1ca-445a-b4ec-29940b56376c'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default=uuid.UUID('1de5caee-4394-49e5-978b-b3c067899581'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.CharField(default=uuid.UUID('0df2652d-ee5c-42dc-b4f6-225d4b97e98a'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.CharField(default=uuid.UUID('35f3eb64-f22a-456d-904b-95116f8899f1'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
