# Generated by Django 5.1.5 on 2025-05-05 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_checkin', '0017_alter_account_id_alter_item_id_alter_loan_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loan',
            name='loan_sdate_ind',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=uuid.UUID('25edd935-51b9-4dab-b3e8-3104bb7b3546'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default=uuid.UUID('bf816176-8be8-4bfc-927a-72a20a1ab5b0'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.CharField(default=uuid.UUID('f4e3753a-4ddb-43dd-bb03-987e10819fe1'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.CharField(default=uuid.UUID('4fd7bb8e-c7c2-45e5-a90b-46223c79a4f3'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['start_date', 'end_date'], name='loan_sdate_ind'),
        ),
    ]
